project:
  type: website
  output-dir: docs

website:
  title: "David Byrne"
  favicon: images/DB_transparent-.png
  navbar:
    title: false
    logo: images/DB_transparent-.png
    search: false
    right:
      - text: "About Me"
        icon: person
        href: about.qmd
      - text: "Projects"
        icon: collection
        href: projects.qmd
      - text: "Certifications"
        icon: award
        href: certifications.qmd
      - text: "CV"
        icon: file-earmark-person
        href: cv.pdf
      - icon: linkedin
        href: https://www.linkedin.com/in/davidbyrnedcu

format:
  html:
    theme: 
      - simplix
      - styles.scss
    mainfont: Montserrat
    toc: false
    page-layout: full
