project:
  type: website
  output-dir: docs

website:
  title: "David Byrne"
  favicon: images/DB_transparent-.png
  navbar:
    title: false
    logo: images/DB_transparent-.png
    search: false
    right:
      - text: "About Me"
        icon: person
        href: about.qmd
      - text: "Projects"
        icon: collection
        href: projects.qmd
      - text: "Certifications"
        icon: award
        href: certifications.qmd
      - text: "CV"
        icon: file-earmark-person
        href: cv.pdf
      - icon: linkedin
        href: https://www.linkedin.com/in/davidbyrnedcu
  page-footer:
    border: false
    left: "© 2025 David Byrne"
    right: >-
      Built using
      <a href="https://quarto.org"
        target="_blank"
        rel="noopener noreferrer"
        style="display:inline-block; vertical-align:middle; margin-left:0.3em;">
        <img src="https://quarto.org/quarto.png"
            alt="Quarto"
            style="height:1em; width:auto; vertical-align:middle;" />
      </a>
    
    

format:
  html:
    theme: [simplex, styles.scss]
    fontawesome: true   
    mainfont: Montserrat
    toc: false
    page-layout: full

