project:
  type: website
  output-dir: docs

website:
  title: "David Byrne"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: hello.qmd
        text: Hello

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



