project:
  type: website
  output-dir: docs

website:
  title: "David Byrne"
  favicon: Dublin City University_transparent-.png
  navbar:
    title: false
    logo: Dublin City University_transparent-.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hello-world.qmd
       

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




