project:
  type: website
  output-dir: docs

website:
  title: "David Byrne"
  favicon: images/DB_transparent-.png
  navbar:
    title: false
    logo: images/DB_transparent-.png
    search: false
    right:
      - text: "About Me"
        icon: person
        href: about.qmd
      - text: "Projects"
        icon: collection
        href: projects.qmd
      - text: "Certifications"
        icon: award
        href: certifications.qmd
      - text: "CV"
        icon: file-earmark-person
        href: cv.pdf
      - icon: linkedin
        href: https://www.linkedin.com/in/davidbyrnedcu

  sidebar:                     
    - title: "Projects"
      contents:
        - projects/business_strat.qmd
        - projects/baa1027_adv_python.qmd    
        - projects/ned.qmd                   
        - projects/programming&visualisation.qmd

format:
  html:
    theme: [simplex, styles.scss]
    fontawesome: true   
    mainfont: Montserrat
    toc: false
    page-layout: full

