project:
  type: website
  output-dir: docs

website:
  title: "David Byrne"
  favicon: DB_transparent-.png
  navbar:
    title: false
    logo: DB_transparent-.png
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Quarto Test"
        href: hello-world.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/davidbyrnedcu
       

format:
  html:
    theme: lux
    css: styles.scss
    toc: true





